config/routes.rb
Rails.application.routes.draw do
  resources :to_dos
  root 'to_dos#index'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:show, :edit, :update, :destroy]

  # GET /to_dos
  # GET /to_dos.json
  def index
    @to_dos = ToDo.all
  end

  # GET /to_dos/1
  # GET /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)

    respond_to do |format|
      if @to_do.save
        format.html { redirect_to @to_do, notice: 'To do was successfully created.' }
        format.json { render :show, status: :created, location: @to_do }
      else
        format.html { render :new }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_dos/1
  # PATCH/PUT /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to @to_do, notice: 'To do was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do.destroy
    respond_to do |format|
      format.html { redirect_to to_dos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = ToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_params
      params.require(:to_do).permit(:task, :description, :done, :actions, :starttime, :address, :gpslatitude, :gpslongitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PropertyTracker</title>
  <%= stylesheet_link_tag  "application", media: "all" %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ToDo</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= "active" if current_page?(controller: 'to_dos') %>"><%= link_to "To-Dos", to_dos_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  <%= javascript_include_tag "application"%>
  <%= yield :additional_javascript %>
</body>
</html>

app/views/to_dos/_form.html.erb
<%= form_for @to_do, :class => "form-horizontal", :role => "form" do |f| %>
  <% if @to_do.errors.any? %>
    <div  class="row" id="error_explanation">
      <h2><%= pluralize(@to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% @to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :starttime, :class => "col-xs-3" %>
    <%= f.text_field :starttime, :class => "col-xs-9" %>
  </div>
  <div class="form-group">
   <%= f.label :done, :class => "col-xs-3" %>
   <%= f.check_box :done %>
  </div>
  <div class="form-group">
    <%= f.label :task, :class => "col-xs-3" %>
    <%= f.text_field :task, :class => "col-xs-9" %>
  </div>
  <div class="form-group">
    <%= f.label :actions, :class => "col-xs-3" %>
    <%= f.text_field :actions, :class => "col-xs-9" %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-xs-3" %>
    <%= f.text_area :description, :class => "col-xs-9" %>
  </div>
 <div class="form-group">
   <%= f.label :address, :class => "col-xs-3" %>
   <%= f.text_area :address, :class => "col-xs-9" %>
 </div>
 <div class="form-group">
   <%= f.label :gpslongitude, :class => "col-xs-3" %>
   <%= f.text_field :gpslongitude, :class => "col-xs-9" %>
 </div>
 <div class="form-group">
   <%= f.label :gpslatitude, :class => "col-xs-3" %>
   <%= f.text_field :gpslatitude, :class => "col-xs-9" %>
 </div>
 
  <div class="form-group">
    <%= f.submit "Save", {class: "btn btn-primary"} %>
    <%= link_to 'Back', to_dos_path, {class: "btn btn-default"} %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Editing to_do</h1>

        <%= render 'form' %>

   </div>
</div>

app/views/to_dos/index.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Listing To Dos</h1>

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Done</th>
              <th>Start Time</th>
			  <th>Task</th>
			  <th>Actions</th>
			  <th>Description</th>
			  <th>Address</th>
			  <th>Longitude</th>
			  <th>Latitude</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @to_dos.each do |to_do| %>
              <tr>
                <td><%= to_do.done %></td>
                <td><%= to_do.starttime %></td>
                <td><%= to_do.task %></td>
				<td><%= to_do.actions %></td>
				<td><%= to_do.description %></td>
				<td><%= to_do.address %></td>
				<td><%= to_do.gpslongitude %></td>
				<td><%= to_do.gpslatitude %></td>
                <td><%= link_to 'Show', to_do, {class: "btn btn-info" } %>
                    <%= link_to 'Edit', edit_to_do_path(to_do), { class: "btn btn-warning" } %>
                    <%= link_to 'Destroy', to_do, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New To do', new_to_do_path, {class: "btn btn-primary"} %>
    </div>
</div>

app/views/to_dos/new.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>New to_do</h1>

        <%= render 'form' %>

   </div>
</div>

app/views/to_dos/show.html.erb
<div class="row">
    <div class="col-xs-12">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Start Time:</strong>
          <%= @to_do.starttime %>
        </p>

        <p>
          <strong>Task:</strong>
          <%= @to_do.task %>
        </p>
		
        <p>
          <strong>Actions:</strong>
          <%= @to_do.actions %>
        </p>
		
        <p>
          <strong>Done:</strong>
          <%= @to_do.done %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @to_do.description %>
        </p>
		
        <p>
          <strong>Address:</strong>
          <%= @to_do.address %>
        </p>
		
        <p>
          <strong>Longtitude:</strong>
          <%= @to_do.gpslongitude %>
        </p>
        <p>
          <strong>Latitude:</strong>
          <%= @to_do.gpslatitude %>
        </p>

       
        <%= link_to 'Edit', edit_to_do_path(@to_do), {class: "btn btn-info"} %>
        <%= link_to 'Back', to_dos_path, {class: "btn btn-default"} %>
    </div>
</div>